version: '3.8' 
services: 
  db: 
    image: postgres:16 
    environment: 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: fincore 
    ports: 
      - "5432:5432" 
  api: 
    build: . 
    ports: 
      - "8080:8080" 
    depends_on: 
      - db