run:
  timeout: 5m
  allow-new-linters: true

output:
  formats:
    - format: colored-line-number

linters-settings:
  gocyclo:
    min-complexity: 15 

  goimports:
    local-prefixes: github.com/martinsdevv/fincore/api 

  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  disable-all: true
  
  enable:
    - govet                
    - goimports            
    - errcheck             
    - staticcheck          
    - unused
    - gocyclo              
    - ineffassign          
    - typecheck            
    - gosimple             
    - bodyclose            
    - unconvert            
    - whitespace           
    - goconst

issues:
  exclude-files:
    - ".*_mock.go"
    - ".*_test.go"

  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - goconst